language: objective-c

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a7cbe520877895f3154a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: true     # default: false
  email:
    on_success: never
    on_failure: change

script: sh build-package.sh

env:
    - APM_TEST_PACKAGES="language-typescript language-csharp"

before_install:
  # Update Homebrew
  - brew update
  # Ruby language support
  - gem install ruby-beautify --verbose
  # Python language support
  - brew install python
  - pip install --upgrade autopep8
  # SQL language support
  - pip install --upgrade sqlparse
  # Markdown language support
  - brew install pandoc
  # Java, C, C++, C#, Objective-C, D, Pawn, Vala
  - brew install uncrustify
  # PHP
#  - pear install PHP_Beautifier-beta
  # CoffeeScript
  - npm install coffee-formatter
